services:
  - type: web
    name: PelisApp-web
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    # Render will build the Docker image using the repository Dockerfile
    startCommand: java $JAVA_OPTS -jar /app/pelisapp.jar
    healthCheckPath: /actuator/health
    instances: 1
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://aws-1-eu-central-2.pooler.supabase.com:6543/postgres?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres.nuewaowsrclicowxxpre
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: APP_JWT_SECRET
        generateValue: true
      - key: APP_ADMIN_PASSWORD
        sync: false
      - key: IMAGES_STORAGE_PROVIDER
        value: local
